"""
Validator agent — checks that the generated spec contains all 7 required
sections.

Matching strategy:
  Look for level-2 headings of the form `## <N>. <anything>` for
  N ∈ {1..7}. We intentionally DO NOT match the title text — section
  titles evolve with every prompt iteration (e.g. "Spring Batch" became
  "Implementation Guidelines — Spring Batch Reference") and each change
  silently broke the validator. The number + dot is the stable contract;
  the Judge prompt enforces the actual title wording.

If a section is missing, it is returned in validation_errors so the
multi_analyst node can retry with targeted feedback.
"""
from __future__ import annotations

import re


# Labels used in the error feedback loop so the Analyst/Judge know what
# section they omitted, not just a bare number.
SECTION_LABELS = {
    1: "Overview",
    2: "Source",
    3: "Transformation",
    4: "Target",
    5: "Lineage",
    6: "Quality",
    7: "Implementation Guidelines (Spring Batch Reference)",
}


# Matches a level-2 numbered heading at the start of a line.
# Example matches: "## 1. Overview", "## 7.   Implementation Guidelines — ..."
_SECTION_HEADING = re.compile(r"^##\s*(\d+)\.\s", re.MULTILINE)


def validate(spec_draft: str) -> tuple[bool, list[str]]:
    """
    Checks that all 7 numbered level-2 sections are present in the spec.

    Args:
        spec_draft: Markdown string generated by the Judge / Analyst.

    Returns:
        (validation_ok, missing_sections)
        validation_ok: True if all 7 sections are present.
        missing_sections: list of human-readable labels for missing
                          sections, e.g. ["## 3. Transformation"] — formatted
                          so the retry prompt reads naturally.
    """
    found_numbers = {int(m.group(1)) for m in _SECTION_HEADING.finditer(spec_draft)}

    missing: list[str] = []
    for n in range(1, 8):
        if n not in found_numbers:
            missing.append(f"## {n}. {SECTION_LABELS[n]}")

    return len(missing) == 0, missing
