"""
Validator agent — checks that the generated spec contains all 7 required sections.

If sections are missing, returns them as validation_errors so the
multi_analyst node can retry with targeted feedback.
"""
from __future__ import annotations

REQUIRED_SECTIONS = [
    "## 1. Overview",
    "## 2. Source",
    "## 3. Transformation",
    "## 4. Target",
    "## 5. Lineage",
    "## 6. Quality",
    "## 7. Spring Batch",
]


def validate(spec_draft: str) -> tuple[bool, list[str]]:
    """
    Checks that all 7 sections are present in the spec.

    Args:
        spec_draft: Markdown string generated by the Judge.

    Returns:
        (validation_ok, missing_sections)
        validation_ok: True if all 7 sections are present.
        missing_sections: list of missing section headers.
    """
    missing = [
        section for section in REQUIRED_SECTIONS
        if section.lower() not in spec_draft.lower()
    ]
    return len(missing) == 0, missing
